src/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  devise_for :staffs
  resources :reservations
  resources :management, only: :index do
    collection do
      resources :stylists
      resources :menus
      resources :galleries, except: [:show, :edit, :update] # only: [:index, :new, :create, :destroy]
      resources :categories, except: :show # only: [:index, :new, :create, :edit, :update, :destroy]
      resources :infos, only: [:show, :edit, :update]
      resources :calculations, only: [:edit, :update]
    end
  end
  # resources :calculations, only: [:edit, :update]
  # resources :infos, only: [:show, :edit, :update]
  # resources :galleries, except: [:show, :edit, :update] #only: [:index, :new, :create, :destroy]
  # resources :menus
  # resources :categories, except: :show #only: [:index, :new, :create, :edit, :update, :destroy]
  # resources :stylists
  # resources :reservations
end

src/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

src/app/models/calculation.rb
# frozen_string_literal: true

class Calculation < ApplicationRecord
  validates :tax, :discount, presence: true
end

src/app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :menu_categories, dependent: :destroy
  has_many :menus, through: :menu_categories

  validates :name, presence: true, uniqueness: true
end

src/app/models/gallery.rb
# frozen_string_literal: true

class Gallery < ApplicationRecord
  validates :image, presence: { message: 'を選択しください' }

  mount_uploader :image, ImagesUploader
end

src/app/models/info.rb
# frozen_string_literal: true

class Info < ApplicationRecord
  # geocoded_by      :address
  # after_validation :geocode
  validates :code, :address, :tel, :weekday, :weekend, :holiday, presence: true
end

src/app/models/menu.rb
# frozen_string_literal: true

class Menu < ApplicationRecord
  has_many :reservations
  has_many :menu_categories, dependent: :destroy
  has_many :categories, through: :menu_categories

  validates :name, :price, presence: true
end

src/app/models/menu_category.rb
# frozen_string_literal: true

class MenuCategory < ApplicationRecord
  belongs_to :menu
  belongs_to :category
end

src/app/models/reservation.rb
# frozen_string_literal: true

class Reservation < ApplicationRecord
  belongs_to :menu
  belongs_to :stylist
  # belongs_to :user

  validates :name, :email, :tel, presence: true
  validates :date, :time, :menu_id, :stylist_id, presence: { message: '選択してください' }

  mount_uploader :image, ImagesUploader
end

src/app/models/staff.rb
# frozen_string_literal: true

class Staff < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

src/app/models/stylist.rb
# frozen_string_literal: true

class Stylist < ApplicationRecord
  has_many :reservations

  validates :name, presence: true
  validates :position, presence: true
  # validates :image, presence: {message: "を選択してください"}

  mount_uploader :image, ImagesUploader
end

src/app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  before_action :phone_num, only: :index

  def index
    @menus = Menu.all
    @categories = Category.all
    @info = Info.find(1)
    @stylists = Stylist.where.not(name: 'No Select')
    @galleries = Gallery.all
  end

  private

  def phone_num
    @phone = Phonelib.parse(Info.find(1).tel, :jp).national
  end
end

src/app/controllers/infos_controller.rb
# frozen_string_literal: true

class InfosController < ApplicationController
  before_action :authenticate_staff!
  # before_action :set_info, only: [:show, :edit, :update]

  # def index
  #   @title = "管理画面"
  # end

  def show
  end

  def edit
    @title = '店舗情報編集画面'
  end

  def update
    if @info.update(info_params)
      redirect_to info_path
    else
      render :edit
    end
  end

  private

  def info_params
    params.require(:info).permit(:code, :address, :tel, :weekday, :weekend, :holiday)
  end

  # def set_info
  #   @info = Info.find(1)
  # end

  # def phone_num
  #   @phone = Phonelib.parse(@info.tel, :jp).national
  # end
end

src/app/controllers/menus_controller.rb
# frozen_string_literal: true

class MenusController < ApplicationController
  before_action :authenticate_staff!
  before_action :set_menu, only: [:show, :edit, :update, :destroy]
  before_action :new_title, only: [:new, :create]
  # before_action :tax_include, only: [:show]

  def index
    @title = 'メニュー一覧'
    @menus = Menu.all
  end

  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.new(menu_params)
    if @menu.save
      redirect_to menu_path(@menu)
    else
      render :new
    end
  end

  def show
  end

  def edit
    @title = 'メニュー編集画面'
    # taxも編集できるようにする
  end

  def update
    @title = 'メニュー編集画面'
    if @menu.update(menu_params)
      redirect_to menu_path(set_menu)
    else
      render :edit
    end
  end

  def destroy
    redirect_to menus_path if @menu.destroy
  end

  private

  def set_menu
    @menu = Menu.find(params[:id])
  end

  def tax_include
    @tax_price = (@menu.price + @menu.price * @tax).ceil
  end

  def new_title
    @title = 'メニュー追加画面'
  end

  # def tax_include_index
  # end

  def menu_params
    params.require(:menu).permit(:name, :price, :comment, category_ids: [])
  end
end

src/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

src/app/helpers/calculations_helper.rb
# frozen_string_literal: true

module CalculationsHelper
end

src/app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

src/app/helpers/galleries_helper.rb
# frozen_string_literal: true

module GalleriesHelper
end

src/app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

src/app/helpers/infos_helper.rb
# frozen_string_literal: true

module InfosHelper
end

src/app/helpers/management_helper.rb
# frozen_string_literal: true

module ManagementHelper
end

src/app/helpers/menus_helper.rb
# frozen_string_literal: true

module MenusHelper
end

src/app/helpers/reservations_helper.rb
# frozen_string_literal: true

module ReservationsHelper
end

src/app/helpers/stylists_helper.rb
# frozen_string_literal: true

module StylistsHelper
end

src/app/views/infos/edit.html.haml
%header
  = render "layouts/management-header"
.Form
  .card
    %h1.card-header 店舗情報編集
    = form_with model: @info, class: "card-body", local: true  do |f|
      - if @info.errors.any?
        %ul.error.white
          %p 必須項目
          - @info.errors.full_messages.each do |message|
            %li= "※#{message}"
      .form-group.card-title
        = f.label :code, "郵便番号" do
          郵便番号
        = f.text_field :code, class: "form-control"
      .form-group
        = f.label :address, "住所" do
          住所
        = f.text_field :address, class: "form-control"
      .form-group
        = f.label :tel, "電話番号" do
          電話番号
        = f.telephone_field :tel, class: "form-control"
      .form-group
        = f.label :weekday, "火曜日〜土曜日" do
          火曜日〜土曜日
        = f.text_field :weekday, class: "form-control"
      .form-group
        = f.label :weekend, "日曜日" do
          日曜日
        = f.text_field :weekend, class: "form-control"
      .form-group
        = f.label :holiday, "定休日" do
          定休日
        = f.text_field :holiday, class: "form-control"
      = f.submit "送信", class: "btn btn-outline-info"

src/app/views/infos/index.html.haml
-# %header
-#   = render "layouts/management-header"
-# .Main
-#   .Main__card
-#     = link_to edit_info_path(@info), class: "Card" do
-#       = image_tag '/images/sample.jpg', width: "425", height: "300"
-#       .Card__Text
-#         %p Meta
-#   .Main__card
-#     = link_to galleries_path, class: "Card" do
-#       = image_tag '/images/sample.jpg', width: "425", height: "300"
-#       .Card__Text
-#         %p Gallery
-#   .Main__card
-#     = link_to "#", class: "Card" do
-#       / linkを訂正する
-#       = image_tag '/images/sample.jpg', width: "425", height: "300"
-#       .Card__Text
-#         %p User
-#   .Main__card
-#     = link_to menus_path, class: "Card" do
-#       = image_tag '/images/sample.jpg', width: "425", height: "300"
-#       .Card__Text
-#         %p Menu
-#   .Main__card
-#     = link_to categories_path, class: "Card" do
-#       = image_tag '/images/sample.jpg', width: "425", height: "300"
-#       .Card__Text
-#         %p category
-#   .Main__card
-#     = link_to reservations_path, class: "Card" do
-#       = image_tag '/images/sample.jpg', width: "425", height: "300"
-#       .Card__Text
-#         %p reservations

src/app/views/infos/show.html.haml
%header
  = render "layouts/management-header"
.Update
  .card
    .alert.alert-secondary
      編集内容を確認してください
    %h3.card-header
      郵便番号
    .card-body
      %h4.card-title
        = @info.code
    %h3.card-header
      住所
    .card-body
      %h4.card-title
        = @info.address
    %h3.card-header
      電話番号
    .card-body
      %h4.card-title
        = @phone
    %h3.card-header
      火曜日〜土曜日
    .card-body
      %h4.card-title
        = @info.weekday
    %h3.card-header
      日曜日
    .card-body
      %h4.card-title
        = @info.weekend
    %h3.card-header
      定休日
    .card-body
      %h4.card-title
        = @info.holiday
    .Btn
      = link_to edit_info_path(@info), class: "btn btn-outline-danger check" do
        編集画面へ戻る
      -# 管理画面へのリンクは後ほど作成
      = link_to management_index_path, class: "btn btn-outline-info check" do
        管理画面へ戻る

src/app/views/menus/_form.html.haml
.Form
  .card
    %h1.card-header
      = @title
    = form_with model: @menu, class: "card-body", local: true, id: "form_menu" do |f|
      - if @menu.errors.any?
        %ul.error.white
          %p 必須項目
          - @menu.errors.full_messages.each do |message|
            %li= "※#{message}"

      .form-group.card-title
        = f.label :name do
          name
        = f.text_field :name, class: "form-control"
      .form-group
        = f.label :price do
          price
        = f.text_field :price, class: "form-control"
      .form-group
        = f.label :comment do
          comment
        = f.text_area :comment, class: "form-control"
      .form-group
        = f.label :category_ids do
          Categories
        .Checkbox
          = f.collection_check_boxes :category_ids, Category.all, :id, :name, class: "form-control" do |b|
            .Checkbox__item#b.text
              = b.label class: "Checkbox__item--btn btn"
              = b.check_box class: "Checkbox__item--hidden"
      = f.submit "送信", class: "btn btn-outline-info"

src/app/views/menus/edit.html.haml
= render partial: "layouts/management-header"
= render partial: "form"

src/app/views/menus/index.html.haml
%header
  = render "layouts/management-header"
.Main
  .list-group.container
    = link_to new_menu_path, class: "list-group-item list-group-item-action  list-group-item-secondary" do
      = icon("fas", "plus")
      追加する
    - @menus.each do |menu|
      = link_to menu_path(menu.id), class: "list-group-item list-group-item-action" do
        = menu.name
        - menu.categories.each do |category|
          = category.name

src/app/views/menus/new.html.haml
= render partial: "layouts/management-header"
= render partial: "form"

src/app/views/menus/show.html.haml
%header
  = render "layouts/management-header"
.Update
  .card
    .alert.alert-secondary
      編集内容を確認してください
    %h3.card-header
      name
    .card-body
      %h4.card-title
        = @menu.name
    %h3.card-header
      category
    .card-body
      %h4.card-title
        - @menu.categories.each do |category|
          = category.name
    %h3.card-header
      comment
    .card-body
      %h4.card-title
        = @menu.comment
    %h3.card-header
      price
    .card-body
      %h4.card-title
        = "¥#{@menu.price}"
    %h3.card-header
      total (tax)
    .card-body
      %h4.card-title
        = "¥#{(@menu.price + @menu.price * @tax).ceil} (#{(@tax * 100).ceil}%)"
    .Btn
      = link_to menu_path(@menu), method: "delete", class: "btn btn-outline-danger check delete" do
        削除
      = link_to edit_menu_path(@menu), class: "btn btn-outline-warning check" do
        編集画面
      = link_to menus_path, class: "btn btn-outline-info check" do
        メニュー一覧へ戻る