src/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  devise_for :staffs
  resources :reservations
  resources :management, only: :index do
    collection do
      resources :stylists
      resources :menus
      resources :galleries, except: [:show, :edit, :update] # only: [:index, :new, :create, :destroy]
      resources :categories, except: :show # only: [:index, :new, :create, :edit, :update, :destroy]
      resources :infos, only: [:show, :edit, :update]
      resources :calculations, only: [:edit, :update]
    end
  end
  # resources :calculations, only: [:edit, :update]
  # resources :infos, only: [:show, :edit, :update]
  # resources :galleries, except: [:show, :edit, :update] #only: [:index, :new, :create, :destroy]
  # resources :menus
  # resources :categories, except: :show #only: [:index, :new, :create, :edit, :update, :destroy]
  # resources :stylists
  # resources :reservations
end

src/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

src/app/models/calculation.rb
# frozen_string_literal: true

class Calculation < ApplicationRecord
  validates :tax, :discount, presence: true
end

src/app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :menu_categories, dependent: :destroy
  has_many :menus, through: :menu_categories

  validates :name, presence: true, uniqueness: true
end

src/app/models/gallery.rb
# frozen_string_literal: true

class Gallery < ApplicationRecord
  validates :image, presence: { message: 'を選択しください' }

  mount_uploader :image, ImagesUploader
end

src/app/models/info.rb
# frozen_string_literal: true

class Info < ApplicationRecord
  # geocoded_by      :address
  # after_validation :geocode
  validates :code, :address, :tel, :weekday, :weekend, :holiday, presence: true
end

src/app/models/menu.rb
# frozen_string_literal: true

class Menu < ApplicationRecord
  has_many :reservations
  has_many :menu_categories, dependent: :destroy
  has_many :categories, through: :menu_categories

  validates :name, :price, presence: true
end

src/app/models/menu_category.rb
# frozen_string_literal: true

class MenuCategory < ApplicationRecord
  belongs_to :menu
  belongs_to :category
end

src/app/models/reservation.rb
# frozen_string_literal: true

class Reservation < ApplicationRecord
  belongs_to :menu
  belongs_to :stylist
  # belongs_to :user

  validates :name, :email, :tel, presence: true
  validates :date, :time, :menu_id, :stylist_id, presence: { message: '選択してください' }

  mount_uploader :image, ImagesUploader
end

src/app/models/staff.rb
# frozen_string_literal: true

class Staff < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

src/app/models/stylist.rb
# frozen_string_literal: true

class Stylist < ApplicationRecord
  has_many :reservations

  validates :name, presence: true
  validates :position, presence: true
  # validates :image, presence: {message: "を選択してください"}

  mount_uploader :image, ImagesUploader
end

src/app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  before_action :phone_num, only: :index

  def index
    @menus = Menu.all
    @categories = Category.all
    @info = Info.find(1)
    @stylists = Stylist.where.not(name: 'No Select')
    @galleries = Gallery.all
  end

  private

  def phone_num
    @phone = Phonelib.parse(Info.find(1).tel, :jp).national
  end
end

src/app/controllers/management_controller.rb
# frozen_string_literal: true

class ManagementController < ApplicationController
  before_action :authenticate_staff!, only: :index

  def index
    @title = current_staff.name
  end
end

src/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

src/app/helpers/calculations_helper.rb
# frozen_string_literal: true

module CalculationsHelper
end

src/app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

src/app/helpers/galleries_helper.rb
# frozen_string_literal: true

module GalleriesHelper
end

src/app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

src/app/helpers/infos_helper.rb
# frozen_string_literal: true

module InfosHelper
end

src/app/helpers/management_helper.rb
# frozen_string_literal: true

module ManagementHelper
end

src/app/helpers/menus_helper.rb
# frozen_string_literal: true

module MenusHelper
end

src/app/helpers/reservations_helper.rb
# frozen_string_literal: true

module ReservationsHelper
end

src/app/helpers/stylists_helper.rb
# frozen_string_literal: true

module StylistsHelper
end

src/app/views/management/index.html.haml
%header
  = render "layouts/management-header"
.Main
  .list-group.container
    .list-group-item.list-group-item-action.list-group-item-secondary.index
      %h2 管理一覧
    = link_to edit_info_path(@info), class: "list-group-item list-group-item-action" do
      店舗情報
    = link_to edit_calculation_path(@calculation), class: "list-group-item list-group-item-action" do
      消費税率・値引率
    = link_to galleries_path, class: "list-group-item list-group-item-action" do
      Galleries
    = link_to stylists_path, class: "list-group-item list-group-item-action" do
      スタイリスト
    = link_to menus_path, class: "list-group-item list-group-item-action" do
      メニュー
    = link_to reservations_path, class: "list-group-item list-group-item-action" do
      予約一覧
























-# .Main
-#   .Main__card
-#     = link_to edit_info_path(@info), class: "Card" do
-#       = image_tag '/images/noselect.jpg'
-#       .Card__Text
-#         %p 店舗情報
-#   .Main__card
-#     = link_to edit_calculation_path(@calculation), class: "Card" do
-#       = image_tag '/images/sample.jpg'
-#       .Card__Text
-#         %p 消費税率・値引率
-#   .Main__card
-#     = link_to galleries_path, class: "Card" do
-#       = image_tag '/images/sample.jpg'
-#       .Card__Text
-#         %p Gallery
-#   -# .Main__card
-#   -#   = link_to "#", class: "Card" do
-#   -#     / linkを訂正する
-#   -#     = image_tag '/images/sample.jpg'
-#   -#     .Card__Text
-#   -#       %p User
-#   .Main__card
-#     = link_to stylists_path, class: "Card" do
-#       = image_tag '/images/sample.jpg'
-#       .Card__Text
-#         %p Stylist
-#   .Main__card
-#     = link_to menus_path, class: "Card" do
-#       = image_tag '/images/sample.jpg'
-#       .Card__Text
-#         %p Menu
-#   -# .Main__card
-#   -#   = link_to categories_path, class: "Card" do
-#   -#     = image_tag '/images/sample.jpg'
-#   -#     .Card__Text
-#   -#       %p category
-#   .Main__card
-#     = link_to reservations_path, class: "Card" do
-#       = image_tag '/images/sample.jpg'
-#       .Card__Text
-#         %p reservations