src/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  devise_for :staffs
  resources :reservations
  resources :management, only: :index do
    collection do
      resources :stylists
      resources :menus
      resources :galleries, except: [:show, :edit, :update] # only: [:index, :new, :create, :destroy]
      resources :categories, except: :show # only: [:index, :new, :create, :edit, :update, :destroy]
      resources :infos, only: [:show, :edit, :update]
      resources :calculations, only: [:edit, :update]
    end
  end
  # resources :calculations, only: [:edit, :update]
  # resources :infos, only: [:show, :edit, :update]
  # resources :galleries, except: [:show, :edit, :update] #only: [:index, :new, :create, :destroy]
  # resources :menus
  # resources :categories, except: :show #only: [:index, :new, :create, :edit, :update, :destroy]
  # resources :stylists
  # resources :reservations
end

src/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

src/app/models/calculation.rb
# frozen_string_literal: true

class Calculation < ApplicationRecord
  validates :tax, :discount, presence: true
end

src/app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :menu_categories, dependent: :destroy
  has_many :menus, through: :menu_categories

  validates :name, presence: true, uniqueness: true
end

src/app/models/gallery.rb
# frozen_string_literal: true

class Gallery < ApplicationRecord
  validates :image, presence: { message: 'を選択しください' }

  mount_uploader :image, ImagesUploader
end

src/app/models/info.rb
# frozen_string_literal: true

class Info < ApplicationRecord
  # geocoded_by      :address
  # after_validation :geocode
  validates :code, :address, :tel, :weekday, :weekend, :holiday, presence: true
end

src/app/models/menu.rb
# frozen_string_literal: true

class Menu < ApplicationRecord
  has_many :reservations
  has_many :menu_categories, dependent: :destroy
  has_many :categories, through: :menu_categories

  validates :name, :price, presence: true
end

src/app/models/menu_category.rb
# frozen_string_literal: true

class MenuCategory < ApplicationRecord
  belongs_to :menu
  belongs_to :category
end

src/app/models/reservation.rb
# frozen_string_literal: true

class Reservation < ApplicationRecord
  belongs_to :menu
  belongs_to :stylist
  # belongs_to :user

  validates :name, :email, :tel, presence: true
  validates :date, :time, :menu_id, :stylist_id, presence: { message: '選択してください' }

  mount_uploader :image, ImagesUploader
end

src/app/models/staff.rb
# frozen_string_literal: true

class Staff < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

src/app/models/stylist.rb
# frozen_string_literal: true

class Stylist < ApplicationRecord
  has_many :reservations

  validates :name, presence: true
  validates :position, presence: true
  # validates :image, presence: {message: "を選択してください"}

  mount_uploader :image, ImagesUploader
end

src/app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  before_action :phone_num, only: :index

  def index
    @menus = Menu.all
    @categories = Category.all
    @info = Info.find(1)
    @stylists = Stylist.where.not(name: 'No Select')
    @galleries = Gallery.all
  end

  private

  def phone_num
    @phone = Phonelib.parse(Info.find(1).tel, :jp).national
  end
end

src/app/controllers/infos_controller.rb
# frozen_string_literal: true

class InfosController < ApplicationController
  before_action :authenticate_staff!
  # before_action :set_info, only: [:show, :edit, :update]

  # def index
  #   @title = "管理画面"
  # end

  def show
  end

  def edit
    @title = '店舗情報編集画面'
  end

  def update
    if @info.update(info_params)
      redirect_to info_path
    else
      render :edit
    end
  end

  private

  def info_params
    params.require(:info).permit(:code, :address, :tel, :weekday, :weekend, :holiday)
  end

  # def set_info
  #   @info = Info.find(1)
  # end

  # def phone_num
  #   @phone = Phonelib.parse(@info.tel, :jp).national
  # end
end

src/app/controllers/reservations_controller.rb
# frozen_string_literal: true

class ReservationsController < ApplicationController
  before_action :authenticate_staff!, only: [:index, :show, :edit, :update, :destroy]
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]
  before_action :set_other, only: [:new, :create, :edit]
  before_action :set_date, only: [:index, :new, :create, :edit]
  before_action :user_phone, only: [:show, :update]
  before_action :price_calculation, only: [:show, :update]

  def index
    @reservations = Reservation.all
    @stylists = Stylist.all # .order(@reservations.date: :desc)
  end

  def new
    @reservation = Reservation.new
    # respond_to do |format|
    #   format.html
    #   format.json
    # end
  end

  def create
    @reservation = Reservation.new(reservation_params)
    if @reservation.save
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @reservation.update(reservation_params)
      render :update
    else
      render :edit
    end
  end

  def destroy
    redirect_to reservations_path if @reservation.destroy
  end

  private

  def set_reservation
    @reservation = Reservation.find(params[:id])
  end

  def set_other
    @stylists = Stylist.all # where(["name LIKE ? ", "%#{params[:keyword]}%"])
    @menus = Menu.all
  end

  def set_date
    @today = Date.current # .days_since(1)
    @week = Date.current # .days_since(1)
    @date = Date.current
  end

  def user_phone
    @user_phone = Phonelib.parse(@reservation.tel, :jp).national
  end

  def price_calculation
    @price = @reservation.menu.price
    @discountPrice = @price * @discount
  end

  def reservation_params
    params.require(:reservation)
          .permit(
            :name,
            :email,
            :tel,
            :date,
            :time,
            :request,
            :image,
            :stylist_id,
            :menu_id
          )
  end
end

src/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

src/app/helpers/calculations_helper.rb
# frozen_string_literal: true

module CalculationsHelper
end

src/app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

src/app/helpers/galleries_helper.rb
# frozen_string_literal: true

module GalleriesHelper
end

src/app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

src/app/helpers/infos_helper.rb
# frozen_string_literal: true

module InfosHelper
end

src/app/helpers/management_helper.rb
# frozen_string_literal: true

module ManagementHelper
end

src/app/helpers/menus_helper.rb
# frozen_string_literal: true

module MenusHelper
end

src/app/helpers/reservations_helper.rb
# frozen_string_literal: true

module ReservationsHelper
end

src/app/helpers/stylists_helper.rb
# frozen_string_literal: true

module StylistsHelper
end

src/app/views/reservations/_carender.html.haml
.Calendar
  %table
    %tbody

      %tr.TableHeader
        %th.Time 時間
        - 7.times do |i|
          %th{class: "#{@week.days_since(i).strftime("%a")}"}
            = @today.days_since(i).strftime("%m/%d (%a)")

      %tr
        %th.Time
          10:00
        - 7.times do |i|
          %td{class: "#{@week.days_since(i).strftime("%a")} Calendar__select"}
            = radio_button_tag "reservation[time]", "10:00"
            = radio_button_tag  "reservation[date]", "#{@date.days_since(i).strftime("%F")}"
            .Status
              %span.Status__value
              %span.check
                = icon("far", "check-square")

      %tr.Color
        %th.Time
          11:00
        - 7.times do |i|
          %td{class: "#{@week.days_since(i).strftime("%a")} Calendar__select"}
            = radio_button_tag "reservation[time]", "11:00"
            = radio_button_tag  "reservation[date]", "#{@date.days_since(i).strftime("%F")}"
            .Status
              %span.Status__value
              %span.check
                = icon("far", "check-square")

      %tr
        %th.Time
          12:00
        - 7.times do |i|
          %td{class: "#{@week.days_since(i).strftime("%a")} Calendar__select"}
            = radio_button_tag "reservation[time]", "12:00"
            = radio_button_tag  "reservation[date]", "#{@date.days_since(i).strftime("%F")}"
            .Status
              %span.Status__value
              %span.check
                = icon("far", "check-square")

      %tr.Color
        %th.Time
          13:00
        - 7.times do |i|
          %td{class: "#{@week.days_since(i).strftime("%a")} Calendar__select"}
            = radio_button_tag "reservation[time]", "13:00"
            = radio_button_tag  "reservation[date]", "#{@date.days_since(i).strftime("%F")}"
            .Status
              %span.Status__value
              %span.check
                = icon("far", "check-square")

      %tr
        %th.Time
          14:00
        - 7.times do |i|
          %td{class: "#{@week.days_since(i).strftime("%a")} Calendar__select"}
            = radio_button_tag "reservation[time]", "14:00"
            = radio_button_tag  "reservation[date]", "#{@date.days_since(i).strftime("%F")}"
            .Status
              %span.Status__value
              %span.check
                = icon("far", "check-square")

      %tr.Color
        %th.Time
          15:00
        - 7.times do |i|
          %td{class: "#{@week.days_since(i).strftime("%a")} Calendar__select"}
            = radio_button_tag "reservation[time]", "15:00"
            = radio_button_tag  "reservation[date]", "#{@date.days_since(i).strftime("%F")}"
            .Status
              %span.Status__value
              %span.check
                = icon("far", "check-square")

      %tr
        %th.Time
          16:00
        - 7.times do |i|
          %td{class: "#{@week.days_since(i).strftime("%a")} Calendar__select"}
            = radio_button_tag "reservation[time]", "16:00"
            = radio_button_tag  "reservation[date]", "#{@date.days_since(1).strftime("%F")}"
            .Status
              %span.Status__value
              %span.check
                = icon("far", "check-square")

      %tr.Color
        %th.Time
          17:00
        - 7.times do |i|
          %td{class: "#{@week.days_since(i).strftime("%a")} Calendar__select"}
            = radio_button_tag "reservation[time]", "17:00"
            = radio_button_tag  "reservation[date]", "#{@date.days_since(i).strftime("%F")}"
            .Status
              %span.Status__value
              %span.check
                = icon("far", "check-square")

      %tr
        %th.Time
          18:00
        - 7.times do |i|
          %td{class: "#{@week.days_since(i).strftime("%a")} Calendar__select"}
            = radio_button_tag "reservation[time]", "18:00"
            = radio_button_tag  "reservation[date]", "#{@date.days_since(i).strftime("%F")}"
            .Status
              %span.Status__value
              %span.check
                = icon("far", "check-square")

      %tr.Color.NineTeeen
        %th.Time
          19:00
        - 7.times do |i|
          %td{class: "#{@week.days_since(i).strftime("%a")} Calendar__select"}
            = radio_button_tag "reservation[time]", "19:00"
            = radio_button_tag  "reservation[date]", "#{@date.days_since(i).strftime("%F")}"
            .Status
              %span.Status__value
              %span.check
                = icon("far", "check-square")

src/app/views/reservations/_create-priceTable.html.haml
%table
  %tbody
    %tr
      %th Menu
      %th 価格
      %th
        ="値引額(#{ (@discount * 100).ceil }%)"
      %th 小計
      %th 消費税率
      %th 消費税
      %th 合計
    %tr.color
      %th
        = @reservation.menu.name
      %td
        = "¥#{ @reservation.menu.price.to_s(:delimited) }"
      %td
        = "- ¥#{ (@reservation.menu.price * @discount).ceil.to_s(:delimited) }"
      %td
        = "¥#{ (@reservation.menu.price - (@reservation.menu.price * @discount).ceil).to_s(:delimited) }"
      %td
        = "#{ (@tax * 100).ceil }%"
      %td
        = "¥#{ ((@reservation.menu.price - (@reservation.menu.price * @discount).ceil) * @tax).ceil.to_s(:delimited) }"
      %td
        = "¥#{ ((@reservation.menu.price - (@reservation.menu.price * @discount).ceil) * (@tax + 1)).ceil.to_s(:delimited) }"

src/app/views/reservations/_form.html.haml
= form_with model: @reservation, local: true, class: "ReservForm__contents", id: "new_reservation" do |f|

  - if @reservation.errors.any?
    %p.error ※選択・入力できていないものがあります

  .ReservForm__contents--stylist
    .StylistHeader
      %h4 Stylist Select
    .StylistContents
      - @stylists.each do |stylist|
        .StylistContents__Box
          .StylistContents__Box--Item
            = f.radio_button :stylist_id, "#{stylist.id}", class: "hidden"
            = f.label :"stylist_id_#{stylist.id}", class: "StylistContents__Box--Item--label" do
              - if stylist.image?
                = image_tag stylist.image.url, class: "Image"
              - else
                = image_tag "/assets/default.jpg", class: "Image", width: "400px", height: "400px"
              %span.check
                = icon("fas", "check")
          .StylistContents__Box--info
            .Info
              .Info__name
                = stylist.name
              - if stylist.position != "No Select"
                .Info__position
                  = stylist.position
            -# .comment
            -#   = stylist.comment

    .BTN.MENU.next
      = icon("fas", "chevron-down")

  .ReservForm__contents--menu
    .MenuHeader
      %h4 Menu select
    .MenuContents
      - @menus.each do |menu|
        .MenuContents__Box
          .MenuContents__Box--Item
            = f.radio_button :menu_id, "#{menu.id}", class: "hidden"
            = f.label :"menu_id_#{menu.id}", class: "MenuContents__Box--Item--label" do
              .Item
                .Item__top
                  .Item__top--name
                    = menu.name
                  .Item__top--price
                    = "¥#{menu.price}(税抜)"
              .Item__buttom
                - menu.categories.each do |category|
                  = category.name
              %span.check
                = icon("fas", "check")

    .BTN.DATE.next
      = icon("fas", "chevron-down")

  .ReservForm__contents--date
    .DateHeader
      %h4 Date select
    .DateContents
      = render "reservations/carender"

    .BTN.USER.next
      = icon("fas", "chevron-down")

  .ReservForm__contents--user
    .UserHeader
      %h4 お客様情報
    .UserContents
      .UserContents__name
        .ItemTitle
        = f.text_field :name, class: "field", placeholder: "お名前 *"
      .UserContents__email
        .ItemTitle
        = f.email_field :email, class: "field", placeholder: "メールアドレス *"
      .UserContents__tel
        .ItemTitle
        = f.telephone_field :tel, class: "field", placeholder: "電話番号 *"
      .UserContents__request
        .Request
          .Request__text
            .ItemTitle
            = f.text_area :request, class: "area", rows: "5", placeholder: "ご要望、ご希望のヘアスタイルがあればご記入ください"
            = f.label :image, class: "imageicon" do
              = icon("fas", "images", class: "imageicon")
            = f.file_field :image, class: "hidden"

    .ReservForm__contents--submit
      = f.submit "入力確認画面へ", class: "send"

src/app/views/reservations/_form2.html.haml
-# -# ajaxで実装する
-# = form_with model: @reservation, local: true, class: "ReservForm__contents" do |f|
-#   .ReservForm__contents--stylist
-#     .StylistHeader
-#       %h4 Stylist Select
-#     .StylistContents
-#       - @stylists.each do |stylist|
-#         = f.collection_radio_buttons :stylist_id, Stylist.all, :id, :name do |b|
-#           -# %label.StylistContents__item
-#             -# = image_tag b.text, class: "StylistContents__item--image click", id: "#{b.text}"
-#           %span.NameModal.StylistContents__item--image
-#             = b.label class: "StylistContents__item click", id: "#{b.text}" do
-#               = image_tag stylist.image_url
-#             = b.radio_button
-#   -# %button.Btn#stylist 次へ
-#   -# .ReservForm__contents--date
-#   -#   = f.label :date do
-#   -#     予約日
-#   -#   = f.date_field :date
-#   -# .ReservForm__contents--date
-#   -#   = f.label :time do
-#   -#     予約時間
-#   -#   = f.time_field :time
-#   -# %button.Btn 次へ
-#   -# .ReservForm__contents--menu
-#   -#   = f.label :menu_ids do
-#   -#     menu
-#   -#   = f.collection_radio_buttons :menu_id, Menu.all, :id, :name
-#   -# %button.Btn 次へ
-#   -# .ReservForm__contents--user
-#   -#   = f.label :name
-#   -#   = f.text_field :name
-#   -# .ReservForm__contents--user
-#   -#   = f.label :email
-#   -#   = f.text_field :email
-#   -# .ReservForm__contents--user
-#   -#   = f.label :tel
-#   -#   = f.telephone_field :tel
-#   -# .ReservForm__contents--request
-#   -#   = f.label :request do
-#   -#     request
-#   -#   = f.text_area :request
-#   -# .ReservForm__contents--request
-#   -#   = f.label :image do
-#   -#     image
-#   -#   = f.file_field :image
-#   -# .ReservForm__contents--submit
-#   -#   = f.submit "送信"

src/app/views/reservations/_priceTable.html.haml
%table
  %tbody
    %tr
      %th Menu
      %th 価格
      %th
        ="値引額(#{ (@discount * 100).ceil }%)"
      %th 小計
      %th 消費税率
      %th 消費税
      %th 合計
    %tr.color
      %th
        = @reservation.menu.name
      %td
        = "¥#{ @price.to_s(:delimited) }"
      %td
        = "- ¥#{ (@discountPrice).ceil.to_s(:delimited) }"
      %td
        = "¥#{ (@price - @discountPrice.ceil).to_s(:delimited) }"
      %td
        = "#{ (@tax * 100).ceil }%"
      %td
        = "¥#{ ((@price - @discountPrice.ceil) * @tax).ceil.to_s(:delimited) }"
      %td
        = "¥#{ ((@price - @discountPrice.ceil) * (@tax + 1)).ceil.to_s(:delimited) }"

src/app/views/reservations/_reservation.html.haml
.ReservationShow__Item
  .Item
    .Item__dateTime
      .Item__dateTime--header.header
        %h4 ご予約内容
      .Item__dateTime--contents
        .Item__dateTime--content
          .Item__dateTime--content--date
            .dateHeader
              %h5 予約日
            .dateContent.bold
              = @reservation.date
          .Item__dateTime--content--time
            .timeHeader
              %h5 予約時間
            .timeContent.bold
              = @reservation.time
    .Item__stylistMenu
      .Item__stylistMenu--contents
        .Stylist
          .stylsit__header.header
            %h4 Stylist
          .stylist__name
            .content
              .img
                - if @reservation.stylist.image?
                  = image_tag @reservation.stylist.image.url
                - else
                  = image_tag "/assets/default.jpg"
              .name.bold
                = @reservation.stylist.name
              - if @reservation.stylist.position != "No Select"
                .position
                  = @reservation.stylist.position
        .Menu
          .Item__menu
            .Item__menu--header.header
              %h4 Menu
            .Item__menu--contents
              .Item__menu--name.bold
                = @reservation.menu.name
              .Item__menu--price.bold
                = "¥#{@reservation.menu.price.to_s(:delimited)}(税別)"
    .Item__request
      .Item__request--header.header
        %h4 Request
      .Item__request--contents
        .Item__request--contents--image
          = image_tag @reservation.image.url if @reservation.image.present?
        .Item__request--contents--text
          .requestContent.bold
            = @reservation.request

    .Item__user
      .Item__user--header.header
        %h4 お客様情報
      .Item__user--contents
        .Item__user--contents--name
          .nameHeader
            %h5 お名前
          .Name.bold
            = "#{@reservation.name} 様"
        .Item__user--contents--email
          .emailHeader
            %h5 メールアドレス
          .Email.bold
            = @reservation.email
        .Item__user--contents--tel
          .telHeader
            %h5 電話番号
          .Tel.bold
            = @user_phone

    .Price
      .Price__header.header
        %h4 支払い想定金額
      .Price__total
        = render "reservations/priceTable"

    .ReservationShow__link
      = link_to reservations_path, class: "send" do
        予約一覧へ戻る
      = link_to edit_reservation_path, class: "send" do
        予約を編集する
      = link_to reservation_path(@reservation), method: "delete", class: "send delete" do
        予約を削除する

src/app/views/reservations/create.html.haml
.ReservationShow.container
  .ReservationShow__header
    %h4 ご予約内容確認
    .ReservationShow__Item
      .Item
        .Item__dateTime
          .Item__dateTime--header.header
            %h4 ご予約内容
          .Item__dateTime--contents
            .Item__dateTime--content
              .Item__dateTime--content--date
                .dateHeader
                  %h5 予約日
                .dateContent.bold
                  = @reservation.date
              .Item__dateTime--content--time
                .timeHeader
                  %h5 予約時間
                .timeContent.bold
                  = @reservation.time
        .Item__stylistMenu
          .Item__stylistMenu--contents
            .Stylist
              .stylsit__header.header
                %h4 Stylist
              .stylist__name
                .content
                  .img
                    - if @reservation.stylist.image?
                      = image_tag @reservation.stylist.image.url
                    - else
                      = image_tag "/assets/default.jpg"
                  .name.bold
                    = @reservation.stylist.name
                  - if @reservation.stylist.position != "No Select"
                    .position
                      = @reservation.stylist.position
            .Menu
              .Item__menu
                .Item__menu--header.header
                  %h4 Menu
                .Item__menu--contents
                  .Item__menu--name.bold
                    = @reservation.menu.name
                  .Item__menu--price.bold
                    = "¥#{@reservation.menu.price.to_s(:delimited)}(税別)"
        .Item__request
          .Item__request--header.header
            %h4 Request
          .Item__request--contents
            .Item__request--contents--image
              = image_tag @reservation.image.url if @reservation.image.present?
            .Item__request--contents--text
              .requestContent.bold
                = @reservation.request

        .Item__user
          .Item__user--header.header
            %h4 お客様情報
          .Item__user--contents
            .Item__user--contents--name
              .nameHeader
                %h5 お名前
              .Name.bold
                = "#{@reservation.name} 様"
            .Item__user--contents--email
              .emailHeader
                %h5 メールアドレス
              .Email.bold
                = @reservation.email
            .Item__user--contents--tel
              .telHeader
                %h5 電話番号
              .Tel.bold
                = @reservation.tel

        .Price
          .Price__header.header
            %h4 支払い想定金額
          .Price__total
            = render "reservations/create-priceTable"

        .ReservationShow__link
          = link_to :back, class: "back" do
            戻る
          = link_to root_path, class: "send" do
            送信

src/app/views/reservations/edit.html.haml
%header
  = render "layouts/management-header"
.Reserv
  .ReservForm.container
    .ReservForm__header
      %h3 予約編集画面
    = render "reservations/form"

src/app/views/reservations/index.html.haml
%header
  = render "layouts/management-header"
.ReservContainer
  -# .NewBtn
  -#   .NewReservation
  -#     = link_to new_reservation_path do
  -#       = icon("far", "calendar-plus")
  -#   .NewStylist
  -#     = link_to new_stylist_path do
  -#       = icon("fas", "user-plus")

  .ReservationsIndex
    - @stylists.zip(1..) do |stylist, i|
      .ReservationsIndex__Stylist
        .ReservationsIndex__Stylist--header
          .name
            %h2= stylist.name
            = link_to new_reservation_path do
              = icon("fas", "plus")
          .position
            - unless stylist.position == "No Select"
              %h5= stylist.position
        .ReservationsIndex__Stylist--Reservations{id: "list#{i}"}
          - stylist.reservations.each do |stylistreservation|
            .Reservation_Link
              = link_to reservation_path(stylistreservation) do
                .Reservation__Link--name
                  .Reservation__Link--dateTime
                    = stylistreservation.date
                    = stylistreservation.time
                  = "#{stylistreservation.name}様"
                  .Reservation__Link--menu
                    = stylistreservation.menu.name
                    = "¥#{(stylistreservation.menu.price).to_s(:delimited)}"
    -# .Reservation
            -# - if @today.strftime("%F") == stylistreservation.date
            -#   - if 10:00
            -#     .Reservation_Link
            -#       = link_to reservation_path(stylistreservation) do
            -#         .Reservation__Link--name
            -#           = "#{stylistreservation.name}様"
            -#           = stylistreservation.menu.name
            -#           = stylistreservation.menu.price
            -#           .Reservation__Link--dateTime
            -#             = stylistreservation.date
            -#             = stylistreservation.time

src/app/views/reservations/new.html.haml
%header
  = render "layouts/reservation-header"
.Reserv
  .ReservForm.container
    .ReservForm__header
      %h3 予約フォーム
    = render "reservations/form"
%footer
  = render "layouts/footer"

src/app/views/reservations/show.html.haml
%header
  = render "layouts/management-header"
.ReservationShow.container
  .ReservationShow__header
    %h4= @title
  = render "reservations/reservation"

src/app/views/reservations/update.html.haml
%header
  = render "layouts/management-header"
.ReservationShow.container
  .ReservationShow__header
    %h4
      = @title
  = render "reservations/reservation"