src/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  devise_for :staffs
  resources :reservations
  resources :management, only: :index do
    collection do
      resources :stylists
      resources :menus
      resources :galleries, except: [:show, :edit, :update] # only: [:index, :new, :create, :destroy]
      resources :categories, except: :show # only: [:index, :new, :create, :edit, :update, :destroy]
      resources :infos, only: [:show, :edit, :update]
      resources :calculations, only: [:edit, :update]
    end
  end
  # resources :calculations, only: [:edit, :update]
  # resources :infos, only: [:show, :edit, :update]
  # resources :galleries, except: [:show, :edit, :update] #only: [:index, :new, :create, :destroy]
  # resources :menus
  # resources :categories, except: :show #only: [:index, :new, :create, :edit, :update, :destroy]
  # resources :stylists
  # resources :reservations
end

src/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

src/app/models/calculation.rb
# frozen_string_literal: true

class Calculation < ApplicationRecord
  validates :tax, :discount, presence: true
end

src/app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :menu_categories, dependent: :destroy
  has_many :menus, through: :menu_categories

  validates :name, presence: true, uniqueness: true
end

src/app/models/gallery.rb
# frozen_string_literal: true

class Gallery < ApplicationRecord
  validates :image, presence: { message: 'を選択しください' }

  mount_uploader :image, ImagesUploader
end

src/app/models/info.rb
# frozen_string_literal: true

class Info < ApplicationRecord
  # geocoded_by      :address
  # after_validation :geocode
  validates :code, :address, :tel, :weekday, :weekend, :holiday, presence: true
end

src/app/models/menu.rb
# frozen_string_literal: true

class Menu < ApplicationRecord
  has_many :reservations
  has_many :menu_categories, dependent: :destroy
  has_many :categories, through: :menu_categories

  validates :name, :price, presence: true
end

src/app/models/menu_category.rb
# frozen_string_literal: true

class MenuCategory < ApplicationRecord
  belongs_to :menu
  belongs_to :category
end

src/app/models/reservation.rb
# frozen_string_literal: true

class Reservation < ApplicationRecord
  belongs_to :menu
  belongs_to :stylist
  # belongs_to :user

  validates :name, :email, :tel, presence: true
  validates :date, :time, :menu_id, :stylist_id, presence: { message: '選択してください' }

  mount_uploader :image, ImagesUploader
end

src/app/models/staff.rb
# frozen_string_literal: true

class Staff < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

src/app/models/stylist.rb
# frozen_string_literal: true

class Stylist < ApplicationRecord
  has_many :reservations

  validates :name, presence: true
  validates :position, presence: true
  # validates :image, presence: {message: "を選択してください"}

  mount_uploader :image, ImagesUploader
end

src/app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  before_action :phone_num, only: :index

  def index
    @menus = Menu.all
    @categories = Category.all
    @info = Info.find(1)
    @stylists = Stylist.where.not(name: 'No Select')
    @galleries = Gallery.all
  end

  private

  def phone_num
    @phone = Phonelib.parse(Info.find(1).tel, :jp).national
  end
end

src/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

src/app/helpers/calculations_helper.rb
# frozen_string_literal: true

module CalculationsHelper
end

src/app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

src/app/helpers/galleries_helper.rb
# frozen_string_literal: true

module GalleriesHelper
end

src/app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

src/app/helpers/infos_helper.rb
# frozen_string_literal: true

module InfosHelper
end

src/app/helpers/management_helper.rb
# frozen_string_literal: true

module ManagementHelper
end

src/app/helpers/menus_helper.rb
# frozen_string_literal: true

module MenusHelper
end

src/app/helpers/stylists_helper.rb
# frozen_string_literal: true

module StylistsHelper
end

src/app/views/layouts/_footer.html.haml
.footer
  %nav.footer__nav
    .footer__nav--header#after
      %h1 Hair salon
    .footer__nav--list
      .List
        .List__address
          = "〒#{@info.code}"
          = "#{@info.address}"
        .List__tel
          = link_to "tel:#{@info.tel}" do
            = icon("fas", "phone-square-alt")
            = @phone
        .List__info
          .List__info--weekday
            = "火曜日〜土曜日 #{@info.weekday}"
          .List__info--weekend
            = "日曜日 #{@info.weekend}"
          .List__info--holiday
            = "定休日 #{@info.holiday}"

src/app/views/layouts/_header.html.haml
.Header
  .Header__Container
    .Header__Container--Title
      .outLine
        Hair salon 
    %ul.Header__Container--List#List
      %li.Link#Top
        = link_to root_path  do
          Top
      %li.Link#Menu
        = link_to "#" do
          Menu
      %li.Link#Stylist
        = link_to "#" do
          Stylsit
      %li.Link#News
        = link_to "#" do
          News
      %li.Link#Reserv
        = link_to new_reservation_path  do
          Resevation
      %li.Link#Acsess
        = link_to "#"  do
          Acsess
      %li.Link#Sns
        = link_to "#"  do
          = icon("fab", "instagram", class: "instagram")

src/app/views/layouts/_management-header.html.haml
.Header
  %nav.navbar.navbar-dark.bg-dark
    %button.navbar-toggler.navbar-toggler-right{"aria-controls" => "navbarColor01", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarColor01", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    .navbar-brand
      = @title

    #navbarColor01.collapse.navbar-collapse
      %ul.navbar-nav.mr-auto
        %li.nav-item.active
          = link_to management_index_path, class: "nav-link" do
            管理画面
            %span.sr-only (current)
        %li.nav-item
          = link_to edit_info_path(@info), class: "nav-link" do
            店舗情報編集
        %li.nav-item
          = link_to edit_calculation_path(@calculation), class: "nav-link" do
            消費税率・値引率編集
        %li.nav-item
          = link_to galleries_path, class: "nav-link" do
            Galleries
        %li.nav-item
          = link_to stylists_path, class: "nav-link" do
            スタイリスト一覧
        %li.nav-item
          = link_to menus_path, class: "nav-link" do
            メニュー一覧
        %li.nav-item
          = link_to reservations_path, class: "nav-link" do
            予約一覧
        %li.nav-item
          = link_to destroy_staff_session_path, method: :delete, class: "nav-link" do
            ログアウト

src/app/views/layouts/_reservation-header.html.haml
%ul.Header__Container--List#LIST
  %li.Link#Top
    = link_to root_path  do
      Top
  %li.Link.STYLIST
    = link_to "#" do
      Stylist
  %li.Link.MENU
    = link_to "#"  do
      Menu
  %li.Link.DATE
    = link_to "#" do
      Date
  %li.Link.USER
    = link_to "#"  do
      User

src/app/views/layouts/application.html.haml
!!!
%html(lang="ja")
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %meta{content: "”width=device-width,initial-scale=1.0″", name: "”viewport”"}/
    %title ReservationApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag controller.controller_name, media: "all"
    = javascript_include_tag "application"
    = stylesheet_link_tag params[:controller] if Rails.application.assets_manifest.assets["#{params[:controller]}.scss"]
    %link{href: "https://fonts.googleapis.com/css2?family=Shadows+Into+Light&display=swap", rel: "stylesheet"}/
    %link{href:  "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css", rel:  "stylesheet", type:  "text/css"}/
    %link{href:  "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css", rel:  "stylesheet", type:  "text/css"}/
    %script{src:  "//cdn.jsdelivr.net/npm/slick-carousel@1.8\n", type:  "text/javascript"}
    %script{crossorigin: "anonymous", integrity: "sha512-ePSfiGQMIzYzXVQLqWoVC3yxVEHIM5Y3EGh9jPNxpf+hPuLtzPdxJX+lTC3ziPMlDgc5OsM4JThxGwN2DkWEeA==", src: "https://cdnjs.cloudflare.com/ajax/libs/pace/1.0.2/pace.min.js"}
  %body
    #warp
      = yield